### ISSUE TITLE
Installing mnelab from conda-forge broke my base conda env.

### ISSUE THREAD

**Issue by mmagnuski** [conda-forge/mnelab-feedstock#2]
Continuing the conda-specific part of the thread from cbrnr/mnelab#33

According to `conda list --revisions` the mnelab revision installed/updated the following packages in my case:
```
2019-07-02 21:21:56  (rev 31)
     ca-certificates  {2019.5.15 -> 2019.6.16 (conda-forge)}
     certifi  {2019.3.9 -> 2019.6.16 (conda-forge)}
     conda  {4.6.14 -> 4.7.5 (conda-forge)}
     openssl  {1.1.1c -> 1.1.1b (conda-forge)}
    +apptools-4.4.0 (conda-forge)
    +bz2file-0.98 (conda-forge)
    +conda-package-handling-1.3.10 (conda-forge)
    +configobj-5.0.6 (conda-forge)
    +dipy-0.16.0 (conda-forge)
    +envisage-4.7.2 (conda-forge)
    +mayavi-4.6.1 (conda-forge)
    +mne-0.18.2 (conda-forge)
    +mnelab-0.1.0 (conda-forge)
    +nibabel-2.4.1 (conda-forge)
    +pydicom-1.2.2 (conda-forge)
    +pyedflib-0.1.14 (conda-forge)
    +pyface-6.1.1 (conda-forge)
    +pysurfer-0.9.0 (conda-forge)
    +python-picard-0.4 (conda-forge)
    +pyxdf-1.15.2 (conda-forge)
    +traits-5.1.1 (conda-forge)
    +traitsui-6.1.1 (conda-forge)
    +vtk-8.1.1
```
I tried to roll-back to the previous revision, but conda gives unexpected errors now, so its time to put it to sleep and get another one.

**Comment by hoechenberger** [comment]
I think this is expected behavior (except for the fact that you couldn't "go back" easily anymore). Please install into a fresh, dedicated environment, as pointed out in https://github.com/cbrnr/mnelab/issues/33#issuecomment-508358444

Closing, as this is not an issue with this package or feedstock `per se`, but rather a generic `conda` or `conda-forge` issue. You may want to ask on the `[conda-forge` gitter channel](https://gitter.im/conda-forge/conda-forge.github.io) for further assistance.
