### ISSUE TITLE
Old noarch version and files in non-standard labels

### ISSUE THREAD

**Issue by cbrnr** [conda-forge/mnelab-feedstock#30]
@hoechenberger just a heads up that https://anaconda.org/conda-forge/mnelab lists v0.6.3 for the three platforms and v0.5.2 for noarch – is this normal? The website also says that "This package contains files in non-standard labels" – this is probably the reason why it lists this strange installation instruction: `conda install -c conda-forge/label/cf202003 mnelab`. Maybe everything is fine, but if not it would be cool if this could be fixed.

**Comment by hoechenberger** [comment]
> v0.6.3 for the three platforms and v0.5.2 for noarch – is this normal?

Yes, as we switched away from `noarch`, so the latest `noarch` package is older than the latest "no-noarch" packages.



> "This package contains files in non-standard labels

I don't think this is a problem. I'm not exactly sure what caused this – I believe it was some automated migration – but it's totally alright to omit the `label` part in the command line when installing the package.

**Comment by cbrnr** [comment]
Is it possible to remove the old `noarch`? The package is pure Python so I think this is rather confusing. I don't understand the label thing either.

**Comment by hoechenberger** [comment]
> Is it possible to remove the old `noarch`?

Maybe, but why should we remove an old version of a package just because it's old? Anyone asking `conda` or `mamba` to install `mnelab` today will get the latest version anyway, which is non-`noarch`.

> The package is pure Python so I think this is rather confusing.

It's not `noarch` anymore because we added macOS-only dependencies, which simply isn't supported in a cross-platform (`noarch`) package…


> I don't understand the label thing either.

Seems it was created automatically as part of a migration, see the [news from 2020-03-18](https://conda-forge.org/docs/user/announcements.html#id2)

**Comment by cbrnr** [comment]
Alright then, if you think that's fine then I'm happy!
